apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z3ve
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-z3ve@sha256:7b2573e74a140f4887db643fd6cdbbdce8727abff89720898acb6d3e7a628b9c
        name: my-nodejs
        resources: {}
status: {}
